AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repository

Parameters:
  WebRepoName:
    Type: String
    Default: hello-sinatra-web
  ApiRepoName:
    Type: String
    Default: hello-sinatra-api

Resources:
  ECRWebRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref WebRepoName
  ECRApiRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ApiRepoName

Outputs:
  HelloSinatraWebRepositoryArn:
    Value: !GetAtt "ECRWebRepository.Arn"
    Export:
        Name: 'HelloSinatraWebRepositoryArn'
  HelloSinatraWebRepositoryUrl:
    Value: !Join [ ".", [ !Ref "AWS::AccountId", "dkr.ecr", !Ref "AWS::Region", !Join [ "/", [ "amazonaws.com", !Ref WebRepoName ] ] ] ]
    Export:
        Name: 'HelloSinatraWebRepositoryUrl'
  HelloSinatraApiRepositoryArn:
    Value: !GetAtt "ECRApiRepository.Arn"
    Export:
        Name: 'HelloSinatraApiRepositoryArn'
  HelloSinatraApiRepositoryUrl:
    Value: !Join [ ".", [ !Ref "AWS::AccountId", "dkr.ecr", !Ref "AWS::Region", !Join [ "/", [ "amazonaws.com", !Ref ApiRepoName ] ] ] ]
    Export:
        Name: 'HelloSinatraApiRepositoryUrl'
